#!/bin/bash
### BEGIN INIT INFO
# Provides:          kafka
# Required-Start:    $all
# Required-Stop:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Kafka service
### END INIT INFO

KAFKA_STATUS=/container/tmp/kafka_status
isRunning="running"
isNotRunning="not running"

isFileExists() {
    echo -n "$(test -f "$1" && echo 1 || echo 0)"
}

getStatus() {
    EXISTS=$(isFileExists $1)
    if [[ "1" == $EXISTS ]]
    then
        STATUS=$(cat $KAFKA_STATUS)
        echo "$STATUS"
    else
        echo "undefined"
    fi
}

start() {
    STATUS=$(getStatus $KAFKA_STATUS)
    if [[ "$STATUS" != "$isRunning" ]]
    then
        /container/kafkadir/bin/kafka-server-start.sh /container/kafkadir/config/server.properties > /dev/null 2>&1 &
        echo -n "$isRunning" > $KAFKA_STATUS
    else
        echo "Kafka is already runnning"
    fi
}
stop() {
    STATUS=$(getStatus $KAFKA_STATUS)
    if [[ "$STATUS" != "undefined" ]]
    then
        if [[ "$STATUS" != "$isNotRunning" ]]
        then
            /container/kafkadir/bin/kafka-server-stop.sh
            echo -n "$isNotRunnung" > $KAFKA_STATUS
        fi
    fi
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
        echo "==== Kafka status ===="
        STATUS=$(getStatus $KAFKA_STATUS)
        echo "app is $STATUS"
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 